### ISSUE TITLE
attempt to free nil nim heap git object

### ISSUE THREAD

**Issue by dumjyl** [disruptek/nimph#110]
```
[~/projects/std-ext]: nimph --version
0.6.15
[~/projects/std-ext]: nimph                                                                                    〈130〉
  f12e5c      std_ext   patch: export usize for c_size_of
attempt to free nil nim heap git object
... # bunch more of those, as many as I have releases?
attempt to free nil nim heap git object
std_ext is missing a tag for version 1.5.2
version 1.5.2 arrived in {invalid}
use the `tag` subcommand to add missing tags
run `nimph doctor` to fix this stuff
[~/projects/std-ext]: nim -v
Nim Compiler Version 1.1.1 [Linux: arm64]
Compiled at 2020-01-16
Copyright (c) 2006-2019 by Andreas Rumpf

git hash: 54bfd69a27db6015e4eb7ed0b57b01b7924be2f6
active boot switches: -d:danger
[~/projects/std-ext]: uname --all
Linux dev-board 4.9.140-tegra #1 SMP PREEMPT Mon Dec 9 22:47:42 PST 2019 aarch64 aarch64 aarch64 GNU/Linux
```
Any ideas? If not i'll try and investigate. maybe an aarch64 thing.

**Comment by disruptek** [comment]
So these are error messages from `gittyup`, which I added while working on the `gc:arc` double-free bug.  I assume that you didn't build `nimph` with `gc:arc`, so that suggests that either `nimph` had some broken logic which is now exposed, or I broke `gittyup` in some subtle way while rewriting it to work in `gc:arc`.

Is there a way for me to reproduce the environment/packages locally?

**Comment by disruptek** [comment]
Also, it follows that you could try downgrading gittyup to 2.1.8.  Nimph may also need a patch downgrade or two.

If you do want to investigate, `-d:debugGit` will dump frees so you can get a sense for where you are in the logic.

**Comment by disruptek** [comment]
Cannot reproduce in 0.6.16; please let me know if it doesn't work. :slightly_smiling_face:
