### ISSUE TITLE
Dependencies rolled to same versions that don't meet requirements

### ISSUE THREAD

**Issue by dumjyl** [disruptek/nimph#117]
version: 0.6.22
```
rolled to #1.5.2 to meet https://github.com/dumjyl/std-ext>=1.6.0
rolled to #0.2.1 to meet https://github.com/dumjyl/clang-tooling-nim>=0.4.1
```

**Comment by disruptek** [comment]
Thanks; I removed releases post-0.6.19 until I can finish this work to support #82 and maybe #97.  I think what we want is timestamp-based sorting of tags, but it's tricky because you want to also catch new tags for stable branches (ie. lesser versions), which show up with later timestamps...

Anyway, it seems much more important that we have negation.
