### ISSUE TITLE
Path error when using choosenim

### ISSUE THREAD

**Issue by kungtotte** [disruptek/nimph#127]
nim.cfg is generated using the variable $nim, creating output like so:
```
--path="$nim/pkgs/markdown-0.8.1/src/"
--path="$nim/pkgs/docopt-0.6.8/src/"
--path="$nim/pkgs/mustache-0.2.1/src/"
```

Running `nimph build` errors out saying it can't find these files:
```... /home/thomas/Code/dtt/src/dtt.nim(5, 8) Error: cannot open file: mustache```

When I run `nim dump` I see the following output:
```
/home/thomas/.choosenim/toolchains/nim-1.0.6/pkgs/mustache-0.2.1/src/
/home/thomas/.choosenim/toolchains/nim-1.0.6/pkgs/docopt-0.6.8/src/
/home/thomas/.choosenim/toolchains/nim-1.0.6/pkgs/markdown-0.8.1/src/
```
The packages are installed inside $HOME/.nimble/pkgs, and according to the output of `nimph build` it should be looking for them there:
```
... Command: "/home/thomas/.nimble/bin/nim" c --noNimblePath -d:NimblePkgVersion=0.3.0 --path:"/home/thomas/.nimble/pkgs/markdown-0.8.1"  --path:"/home/thomas/.nimble/pkgs/docopt-0.6.8"  --path:"/home/thomas/.nimble/pkgs/regex-0.13.0"  --path:"/home/thomas/.nimble/pkgs/unicodedb-0.7.2"  --path:"/home/thomas/.nimble/pkgs/unicodeplus-0.5.1"  --path:"/home/thomas/.nimble/pkgs/unicodedb-0.7.2"  --path:"/home/thomas/.nimble/pkgs/mustache-0.2.1"  -o:"/home/thomas/Code/dtt/bin/dtt" "/home/thomas/Code/dtt/src/dtt.nim"
```

If I manually change `nim.cfg` as follows then `nimph build` works without errors:
```
--path="$HOME/.nimble/pkgs/markdown-0.8.1/src/"
--path="$HOME/.nimble/pkgs/docopt-0.6.8/src/"
--path="$HOME/.nimble/pkgs/mustache-0.2.1/src/"
```

I let nimph install these dependencies for me and they were correctly put inside $HOME/.nimble/pkgs, but when building it errors out entirely saying it can't find them.

**Comment by disruptek** [comment]
`nimph build` isn't a thing -- nimph just calls `nimble build` with a suitable `$NIMBLE_DIR`.  I don't know if `nimble` knows anything about `nim.cfg` and, ironically, `nimble` knows nothing about `--nimblePath` as far as I know.

When `nimph doctor` runs, it tries to add `--path` statements which enable packages already in your `--nimblePath` that, due to the way Nimble demands that we structure our packages, are not importable by the Nim compiler.

When adding any such `--path`, nimph uses the shortest substitution -- `$nim` and `$home` are both valid, but `$nim` is obviously a little shorter when your `$nim` is in fact within your `$home`.

You see these targets in `nim dump` because they've been added by nimph, and if you write a `.nim` file that simply does `import mustache`, it should work -- provided your `nim.cfg` is getting picked up (as it would, by default), et cetera...

So, I don't see a bug with nimph here.  If you can demonstrate misbehavior without using `nimble`, that'd be something we should look at!

**Comment by kungtotte** [comment]
This is definitely an issue with how nimph has managed the packages. I had no issues of this kind until I had let `nimph doctor` do its thing.

Starting with a bare nimble repo and a file that just included "import mustache", with the mustache package being installed via nimph yields the error.

[nimcfg_repro.nim](https://paste.sr.ht/%7Ekungtotte/ad23fca6c91b4d3f4eca6561da6bbd482ae27a54)

Reinstalling the mustache package fixes the issue:
https://paste.sr.ht/%7Ekungtotte/db5740835f4506751daa29f7d7d3ef1583ace868

Removing mustache that's been installed and letting `nimph doctor` fix the missing dependency:
https://paste.sr.ht/%7Ekungtotte/fdc3996c62ca6c99e631d2e87b2b82a5743fc226

This generated the following nim.cfg:
[nim.cfg](https://paste.sr.ht/%7Ekungtotte/3d3d745d6c958267853f4b9e31c233b43f4f132e)

As you can see, errors out despite trying to compile it straight via nim and you can see that it's picking up the project-local `nim.cfg`.

So if we modify `nim.cfg` like so:
https://paste.sr.ht/%7Ekungtotte/140f6c6d03263126d86605b36b00520e2d0bb05c

All of a sudden it works.

The rest of my system (choosenim, nim, nimble) is untouched. The only thing that is happening is that I am either installing the package directly via nimble or via nimph. If the package is installed via nimph I have to modify `nim.cfg` to point specifically at `$HOME/.nimble` instead of `$nim` and then everything works, regardless of how I try to compile. If I remove the package and install it via nimble then it will compile even if I don't have a `nim.cfg` file, if the `nim.cfg` file points to $HOME/.nimble, or if it points to $nim.

Something must be happening in the way nimph handles packages to make them error out unless provided with a particular --path. Either we investigate what that is or `nim.cfg` should be generated with a different path, because as this stands I can't use nimph.

**Comment by kungtotte** [comment]
I did some further investigating and it looks like it's due to the package structure of a specific mustache version and the unpinned #master version of mustache.

https://paste.sr.ht/%7Ekungtotte/b7f26d9ab1f5fc0adb7336fc669062fd9a02fec2

Here you can see that master uses the pkg/src/ style and 0.2.1 just dumps everything into the package directory.

pkg/src/ *will fail* unless you do the `nim.cfg` work-around I mentioned above, whereas the old style of packaging works regardless of what's in your `nim.cfg`.

I think nimph should handle this.

PS. I verified this by installing mustache-#master using `nimph doctor` and then manually moving the  .nim files up out of src/ and into the top level mustache-#master directory. Then everything worked even though nim.cfg contained a $nim/ path.

**Comment by disruptek** [comment]
If the `.nimble` file indicates that the `srcDir` is under `./src/` then nimph will use that to determine the source location and successfully setup a path for it.

We can edit the `--path`, sure, but the idea behind nimph is to expose the power of the compiler that is hidden behind nimble.

If the package has a funky structure, there's really nothing we can or should do about that.  We need to be able to support multiple `.nimble` files within a single git repository.  Is the only solution to traverse the entire repository to find a `.nimble` file?  Because I'm not inclined to implement that...

Is the problem simply that the package author neglected a `srcDir` statement?

**Comment by disruptek** [comment]
I think you suggested that choosenim puts its packages _beneath_ `$nim`.  Since nimph thinks that `$nim` belongs to the compiler, it might be confused by this.  I don't use choosenim, so I haven't encountered this.

**Comment by kungtotte** [comment]
The .nimble file of these packages contains a `srcDir` statement, but when they're installed via `nimble install <pkg>` the directory structure does *not* look the same as when they're installed via nimph.

[Here you can see the difference](https://paste.sr.ht/%7Ekungtotte/29ecf445661e39ca77cf3935bbd7b4f6fb52fcb4), as you can see from the .nimble files they're identical and they're both the same version and everything, the only differences are in nimblemeta.json and the file/folder structure. I tried copying the nimblemeta.json file from the nimble-installed package to the nimph-installed package and the error persists, so I don't think it's that.

I have no idea why nimble installs the package like that, but it works when you run entirely via nimble and don't include nimph at all, even when using choosenim to manage nim.

As for the whole `$nim` thing, it seems to be an issue with how that is resolved. `nim dump` tells me that `--path=$nim/pkgs/<pkg>` resolves to `$HOME/.choosenim/toolchains/nim-1.0.6/pkgs/<pkg>` but the package is actually installed at `$HOME/.nimble/pkgs/<pkg>`. If I manually point it to the correct path then it works fine and if the package was installed via nimble and not nimph then any way I want to build it will build just fine even if I don't have a `nim.cfg` with a path argument.

I think this is a case where nimph should gracefully handle being used alongside the two most popular ways of managing nim environments, namely choosenim and nimble. Since setting --path differently in `nim.cfg` works well to work-around this issue, maybe that's what nimph should do?

**Comment by disruptek** [comment]
I created Nimph in part because Araq (and others, including myself of course) dislike the `nimble install` **feature** that changes the directory structure, removes tests and documentation, and otherwise corrupts the very useful git metadata that we know and love.  For folks that want this behavior, `nimph install` provides it -- by simply running `nimble install` while pointing at your most-relevant `--nimblePath`.  That's a convenience feature.

So, with regard to the first issue, `nimble` has some specific "installation" behavior that is provided by the `install` subcommand.  Nimph doesn't have an `install` subcommand, so if you run `nimph install`, you are really running `nimble --nimbleDir=somewhere install`.  This is why new packages are added to the project's compiler environment with `nimph clone` -- because you're basically performing a `git clone` of the package repository.

If the compiler (ie. `nim dump`) resolves `$nim` to `$HOME/.choosenim/toolchains/nim-1.0.6` and that's not where Nim itself is installed, then that _could be_ a bug in the compiler -- see below.  You would want to remove or alter any `nim.cfg` to test this.

If Nimble installs the package to `$HOME/.nimble/pkgs/<pkg>` and then Nimph writes a `nim.cfg` stating that it's installed in `$nim/pkgs/<pkg>` and it's not, then that's definitely a bug in Nimph.

This could have something to do with the Nimph change @alaviss introduced which redefines how we determine the path to the compiler.  It's a tricky situation, because depending upon which compiler is used to build Nimph, the behavior may differ (because Nimph uses the compiler itself as a library).

I will try to take a look at this tomorrow, but I have to warn you -- I care very little for how Nimble works and its design decisions have increasingly little weight in how Nimph evolves.  Nimph supports much more sophisticated behavior enabled by the compiler and it's far more important to me that we exploit the compiler's semantics consistently and transparently.

The whole idea behind Nimph is that you should be able to build your software using a simple `nim c project.nim` command, without regard to your dependencies or their whereabouts.  That's why Nimph manipulates the `nim.cfg` -- this is the mechanism Nimble, Nim, and Nimph have agreed to use for configuring the site-or-project-local compiler environment.

If this simple build command is not working for you, then **that is a defect as far as I'm concerned** -- not a problem to be worked-around.  It's a problem I intend to fix, and promptly, whether it be an error in Nimph, Nim, or the particular package you're trying to use.

I can only support Nimph and Nim, though; not nimble or choosenim.  If you want what they offer, then Nimph probably isn't super useful for you (and vice-versa).

**Comment by kungtotte** [comment]
I don't care about **nimble** as such, I'd use nimph if it actually worked for me.

At this point I'm not going to compromise on using choosenim though. I want a distro-agnostic tool to manage multiple nim toolchains for testing purposes and right now that's choosenim. If you're always running the latest nightly or you're fine with whatever the current version in your distro is then it doesn't matter. I want to have at least 1.0.*x*, 1.2.*x*, and *devel* installed though so I can test that my code runs on released versions and develop against upcoming features.

It's the officially recommended way to install nim.

So I have the binaries in $HOME/.nimble/bin and *choosenim* will swap those out as necessary, but `nim dump` points to where the files actually live which is under the $HOME/. choosenim directory as seen above. 

I'm on mobile now but I've posted everything above already.

Everything works if I change the path in nim.cfg to not base off of `$nim` and instead go by `$HOME/.nimble`.

I don't know if it's a bug how `$nim` resolves when using choosenim or if it's intended behaviour, but that's the core of this issue.

As I said upthread: if you want people to use this tool and have it be adopted, it needs to play nice with the most popular and recommended method of installing Nim. I can investigate some more tonight CEST, and possibly file a bug report against choosenim if `$nim` turns out to be broken from their end.

If this is their intended behaviour, it's something you need to worry about with nimph.

**Comment by Araq** [comment]
> If the compiler (ie. nim dump) resolves $nim to $HOME/.choosenim/toolchains/nim-1.0.6 and that's not where Nim itself is installed, then that could be a bug in the compiler -- see below. 

Totally agree and be ensured that I'm watching this too.

**Comment by alaviss** [comment]
FWIW, choosenim uses shim binaries in order to work on Windows (symlinks won't cut it there), so `findExe"nim"` will point to the shim binary instead of the compiler actual location, messing up $nim detection.

I don't really have any good way to solve this without being dependant on the compiler that built nimph.

**Comment by Araq** [comment]
Oh my, I forgot about the shim binaries... Terrible solution, why not have "nim-selected" in the $PATH and ``choosenim 1.2`` renames "nim-1.2" to "nim-selected". No shims required, no symlinks required.

**Comment by genotrance** [comment]
Basic question - what told nimph to put $nim as the path to pkgs in the first place?

**Comment by disruptek** [comment]
So I guess the bug is that `choosenim` breaks `$nim` with or without Nimph.  I just looked at Nimph and as far as I can tell, it's working correctly as intended.

https://github.com/disruptek/nimph/blob/master/src/nimph/config.nim#L409

**Comment by kungtotte** [comment]
Yes, it's something to do with that. 

I tried removing choosenim altogether and manually installed two separate toolchains (1.0.6, 1.2.0) in separate locations, then wrote a simple shellscript to switch symlinks inside `$HOME/.nimble/bin` to point to a particular toolchain and now it works fine. It spits out some warnings but everything installs fine, compiles fine, etc. regardless of how I install or compile and `nim dump` returns the proper paths.

**Comment by disruptek** [comment]
Great, glad you figured it out!  Maybe file a bug report at choosenim?

**Comment by genotrance** [comment]
Using [findExe("nim")](https://github.com/disruptek/nimph/blob/master/src/nimph/config.nim#L106) is the issue as @alaviss already pointed out. But this is how choosenim works for the last 3 years and has an established user base. Not testing with choosenim or telling people not to use it when it is a legitimate option for users is confusing and not good for the ecosystem. nimph should learn to coexist with these tools.

If `findExe("nim")` turns out to be in `~/.nimble/bin` and no `lib` directory exists there and `~/.choosenim/current` exists then simply use that directory as $nim.

**Comment by disruptek** [comment]
We'll fix this by parsing the `nim dump` output to determine the `prefixDir` for the configuration parser.

**Comment by genotrance** [comment]
https://github.com/nim-lang/Nim/pull/13876

**Comment by disruptek** [comment]
We only care about `prefixDir`.

**Comment by disruptek** [comment]
I just want to thank you all for persisting to get this fixed.  :wink:

**Comment by genotrance** [comment]
Thanks for fixing it - will make nimph accessible to more users and that's most important.

**Comment by kungtotte** [comment]
Most importantly I think it's easier to make nimph work around this issue than to fix the rest of the ecosystem, and this enables more people to use correct package formats instead of mangled installs via nimble.

That will ultimately lead to a better ecosystem quicker 👍

**Comment by genotrance** [comment]
I don't think that's necessarily true - it brought out a discussion on symlinks and shims in choosenim but no real alternative came out that could replace them. Hopefully longer term, we get an improvement there as well. Like disruptek said, others can also run into this in their code.

**Comment by dom96** [comment]
> Terrible solution, why not have "nim-selected" in the $PATH and choosenim 1.2 renames "nim-1.2" to "nim-selected". No shims required, no symlinks required.

One possible problem:

https://irclogs.nim-lang.org/05-04-2020.html#16:28:58

Another is that it's not as clean, you will need to add more directories to your PATH.

Also, just so you know, it's not just choosenim that does this. Rustup does it too.

**Comment by disruptek** [comment]
For spelunkers arriving here in the future, a `choosenim` was added to Nimph which uses the same `prefixDir` hack on compilers that support it.

https://github.com/disruptek/nimph/blob/master/choosenim

**Comment by Araq** [comment]
> https://irclogs.nim-lang.org/05-04-2020.html#16:28:58 (later ryukoposting confirmed that Windows does not let you do this)

Well all it means is that ``choosenim.exe`` itself cannot move the very directory it's in. So have more than a single PATH entry.

**Comment by dom96** [comment]
@Araq I don't see how this can work, we already discussed the necessity to have another PATH entry, but even with that you still need to rename the directory that nim.exe is in which can break when nim.exe is in use (or nimsuggest, nimpretty etc.)

**Comment by Araq** [comment]
If I run ``choosenim 1.2`` and some running processes from 1.0 exist an error during the version swich is perfectly acceptable. How is not even noticing the potential problem preferable in this situation.

**Comment by dom96** [comment]
I disagree, I can see this being a pain in the ass. When I just want to switch to 1.0 quickly from devel I do not care that the darn VS Code plugin is running nimsuggest.exe. I might know that VS Code is to blame, but I doubt most users will.

This coupled with the extra need to add more PATH entries and the fact that the current solution is already implemented and works reasonably well means that your suggestion doesn't bring enough benefits to warrant replacing the current mechanism.

**Comment by disruptek** [comment]
The issue is fixed.  The fix has been outlined for other tools.  A new choosenim is provided that both uses the fix and does not suffer from the same design defect.  Moreover, the new choosenim doesn’t require more than one path addition.

It’s a boring bug that too many people have already spent too much time rehashing.  Please debate other choosenim behavior with interested parties in another repo.

PS.  Copying bad design is not good design.  I don’t care how Rust works if it doesn’t work for me.  And it doesn’t work for me.

**Comment by Araq** [comment]
Alright, I'm quiet now.
