### ISSUE TITLE
nimph is racist

### ISSUE THREAD

**Issue by disruptek** [disruptek/nimph#143]
The `master` -> `main` change and associated default branch name support in libgit2-1.1.0 precipitate a change in Nimph as well.

**Comment by nocturn9x** [comment]
Are you serious or what? Lol, then you hate cats because your pfp is a dog?

**Comment by Yardanico** [comment]
:crab:

**Comment by disruptek** [comment]
I like my software to work, and I believe there will be scenarios where Nimph no longer does the right thing because not only is the default branch not always `master`, but the default branch for new projects on GitHub has been `main` for a few weeks now.

**Comment by omniboy** [comment]
<img width="739" alt="Screenshot 2020-11-03 230303" src="https://user-images.githubusercontent.com/64563583/102019018-1e119680-3d71-11eb-9fb1-3030cc18cc44.png">

**Comment by nocturn9x** [comment]
@omniboy Totally agree. And we should be the smart guys, lol!

**Comment by omniboy** [comment]
Generally speaking, nobody is going to walk up to you and thank you for changing the name of the default branch to `main`, heck I bet they won't even notice it, the people that wanted this to happen. Those people that made this get green lit are the loud minority. The only thing you'll prolly get from this is a backlash because you're – in a sense – advocating for, just like mentioned in the screenshot, mixing IRL bullshit with tech, which is kind of isolated from racism, inequality and more, and should remain that way.

I'm not advocating for "racism". In fact, I think it's unacceptable and I'll be first in line to defend black people etc. but what is happening right now, with this default branch name change, is just stupidity at its finest. This was a move done by GitHub in order to not get a backlash. IMO, there's no linkage between the "master" as in the slave master and the "master" as the default branch name.

**Comment by disruptek** [comment]
Of course.  But who gives a shit?

What matters is that the software works.  I cannot be sure it does when a constant in the code may exist pointing towards a branch that doesn't exist.

I named my mumble server uberalles.  I'm well aware of the danger of ceding language the the right simply because they utter the words.  Fuck those kids.

But this is not that.  It's just a cheeky issue title.  And it will remain until the technical problem it addresses is confirmed fixed.

**Comment by disruptek** [comment]
Let's wait to see if a bug is actually reported; `master` does not exist in the source code.
