### ISSUE TITLE
Exception: 'version' is not accessible using discriminant 'kind' of type 'Release'

### ISSUE THREAD

**Issue by moigagoo** [disruptek/nimph#99]
1. Installed nimph on Windows by running the lines in bootstrap.sh one by one manually, making necessary adjustments to port sh to pwsh.
2. Run `nimph`.

This error comes out:
```Exception: 'version' is not accessible using discriminant 'kind' of type 'Release'```

**Comment by disruptek** [comment]
So the problem seems to be that if any Nimble package in your path (which includes `~/.nimble/pkgs` by default) is broken, Nimph cannot evaluate the project because `nimble dump` pukes on it.

The workaround, for now, is to create a `nim.cfg` with `--clearNimblePath` to omit the default package environment and use local dependencies until we can warn about such errors.

Also note that nimph-0.6.3 may help.

The permanent fix is for Nimph to do its own nimscript parsing of the `.nimble` files, which will happen "soon".

#98 #24

**Comment by disruptek** [comment]
Also, if you can tell me how to adjust the bootstrap for Windows, we can provide that for other Windows folks...

**Comment by disruptek** [comment]
Also, please try 0.6.4 which I just pushed; it will convert 2 and 4-digit version numbers to 3-digits for the purposes of semver...

cc @zevv

**Comment by zevv** [comment]
Fixed! closes #99

**Comment by disruptek** [comment]
Guess we'll close it for now.  Thanks for the report!

**Comment by moigagoo** [comment]
@disruptek First, thanks for the quick fix, that was really fast! 🚀

Second, I've submitted a PR with your bootstrap script ported to PowerShell: #100 .

**Comment by moigagoo** [comment]
@disruptek 

> Also, please try 0.6.4 which I just pushed; it will convert 2 and 4-digit version numbers to 3-digits for the purposes of semver...

For some reason, when I'm installing Nimph, version 0.6.3 get installed.

**Comment by moigagoo** [comment]
> For some reason, when I'm installing Nimph, version 0.6.3 get installed.

Or is it just `nimph --version` that yields the wrong version?
